Katerina-Shemet-Homework15
BeetrootAcademy-DenysKniaziev/csharp-20221129 pull request #134
Opened 2023-01-13 08:10 UTC by Sedjex

2023-01-18 10:54 UTC, SteranOo requested changes
Need to implement your own Stack class

2023-01-20 09:50 UTC, Sedjex commented
Updated

2023-01-22 14:43 UTC, SteranOo commented on Katerina Shemet/Lesson15.Homework/Program.cs
> +    public T[] arr = new T[10];
should not be public to prevent direct access to data, it breaks incapsulation

2023-01-22 14:44 UTC, SteranOo commented on Katerina Shemet/Lesson15.Homework/Program.cs
> +            T[] tmp = new T[arr.Length * 2];
Also you can use Array.CopyTo() or Array.Resize() methods

2023-01-22 14:44 UTC, SteranOo commented on Katerina Shemet/Lesson15.Homework/Program.cs
> +            Console.WriteLine("Empty");
should throw exception instead of console write

2023-01-22 14:45 UTC, SteranOo commented on Katerina Shemet/Lesson15.Homework/Program.cs
> +        return arr[amount - 1];
What if amount == 0?

2023-01-22 14:45 UTC, SteranOo approved these changes

2023-01-22 14:45 UTC, merged