RomanBychkov homework24
BeetrootAcademy-DenysKniaziev/csharp-20221129 pull request #186
Opened 2023-02-07 03:02 UTC by RomanNoname

2023-02-13 09:56 UTC, SteranOo commented on Roman Bychkov/Lesson24/CalendarApp/CalindarTest/UnitTest1.cs
> +    public class UnitTest1
Name of test class should correspond to class that you test (ex. RoomServiceTests, ...)

2023-02-13 09:56 UTC, SteranOo commented on Roman Bychkov/Lesson24/CalendarApp/StringUtils/UnitTest1.cs
> +    public class UnitTest1
The same

2023-02-13 09:57 UTC, SteranOo requested changes
Name of test project should be CalendarApp.BLL.Tests

2023-02-14 23:20 UTC, RomanNoname commented
All done

2023-02-23 15:59 UTC, SteranOo approved these changes

2023-02-23 15:59 UTC, merged